### ISSUE TITLE
Rock bounding boxes look derptastic with random offset

### ISSUE THREAD

**Issue by theishiopian** [Jonathing/ForageCraft#48]
The bounding boxes need to be able to adjust to the offset. Is there a way to get the offset amounts?

**Comment by theishiopian** [comment]
temporary solution currently implemented, still would be cool to have dynamic hitboxes though.

**Comment by JonathanTheInsane** [comment]
I’ve looked at Minecraft’s torch code and I’ll see if I can replicate what
Mojang did when it came to which way a block is placed.

**Comment by theishiopian** [comment]
Good point, I forgot about that. Also, the trapdoor might be a place to look

In the mean time, the bounding boxes I have currently are less terrible.

**Comment by JonathanTheInsane** [comment]
Gotcha fam

**Comment by Jonathing** [comment]
Closing as this probably got indirectly fixed or resolved in 2.0.0.
