### ISSUE TITLE
Configuration file issue - disabling rocks doesn't work

### ISSUE THREAD

**Issue by JTBlum** [Jonathing/ForageCraft#54]
I manually edited the config file for ForageCraft to disable rocks before starting a new world, and I still get a ton of them. I'm not sure if the problem is that it only disables them on worldgen and leaves the random ones from soil etc, or if they show up in worldgen. It's been a few days since Iooked at the issue.

Created as per the request in #53

**Comment by theishiopian** [comment]
Thanks, Jonathan will take a look when he feels better.

**Comment by Jonathing** [comment]
Closing as this probably got indirectly fixed or resolved in 2.0.0.
