### ISSUE TITLE
Configurable Drops

### ISSUE THREAD

**Issue by UnlimatedStone9** [Jonathing/ForageCraft#56]
Hey there, I was wondering is it possible that you could create a way of configuring what can be dropped from what block and what its rarity would be, the config script the player would then input may look something like this:

Block  -----------   Drop   --   Rarity

minecraft:stone-minecraft:bone@4

(4 being 4% chance etc)

**Comment by Jonathing** [comment]
Added support for datapacks in 0445528df750c585dfd3c944af95cf3c754016be so you'll be able to add your own drops that way. It's time to close the book on this three-year-old issue.
