### ISSUE TITLE
Rock Dupe Bug

### ISSUE THREAD

**Issue by RealArcanePhysics** [Jonathing/ForageCraft#58]
This may be a little messy, so sorry. Anyways, rocks will duplicate if they are mined with a pickaxe and then have the block under it break. After the block that was under the rock is broken, the rock is duped and falls. I've been unable to do this with other tools. MairanDS(he's on the Discord) originally found this bug, which caused me to test it myself. He also put a video demonstrating the bug: [https://www.youtube.com/watch?v=DbgEb1rNMwQ](https://www.youtube.com/watch?v=DbgEb1rNMwQ)

**Comment by theishiopian** [comment]
I'll fix this when I split the mod into modules after 1.14. If there's enough demand, might do it sooner once winter quarter is over.

**Comment by Jonathing** [comment]
Closing as this probably got indirectly fixed or resolved in 2.0.0.
