### ISSUE TITLE
Right Click with a stick/Configured Feature not registered/Console Output when breaking blocks 

### ISSUE THREAD

**Issue by ColdFang** [Jonathing/ForageCraft#63]
I noticed a few things when testing Foragecraft 2.0.0 for 1.16.4
Forge Version: 35.1.9

1. When opening chest, doors etc. with a stick in hand, its trying to place it or is placing it. 
2. The Blame Mod puts this in the log, dont know if  this is a problem: https://pastebin.com/jRmuXvEb
3. When breaking blocks the console outputs every block. Not sure if this is necessary or can be hidden
![Bug1](https://user-images.githubusercontent.com/13708113/102340858-509cd880-3f97-11eb-97ea-e47a18643b67.png)

Anyway, thank you for updating Foragecraft! 
Hope its ok to put all 3 things in one post

**Comment by Jonathing** [comment]
Next time try and separate the bugs into separate issues, please!

> When opening chest, doors etc. with a stick in hand, its trying to place it or is placing it.

Noted.

> The Blame Mod puts this in the log, dont know if this is a problem: https://pastebin.com/jRmuXvEb

Ok, sure. I made it a configured feature for this specific reason and I thought I registered it but I guess not.

> When breaking blocks the console outputs every block. Not sure if this is necessary or can be hidden

Probably debug code that I forgot to remove. Noted.

**Comment by ColdFang** [comment]
Sorry, will do! Thank you

**Comment by Jonathing** [comment]
See the above issues.

**Comment by Jonathing** [comment]
All of the bugs in this original issue have been addressed and fixed.
