### ISSUE TITLE
Stick block breaks when neighbor blocks updated

### ISSUE THREAD

**Issue by WenXin20** [Jonathing/ForageCraft#71]
`Minecraft v1.16.4`
`Forge v35.1.13`
`Foragecraft v2.1.0`

If two sticks are placed next to each other, they both break off into an item. Same if a block is broken next to a stick block.

**Comment by Jonathing** [comment]
I'm going to talk to theishiopian about this soon. I was under the impression that this was an intentional design choice but if it isn't, I'll quickly remove it from the mod and release a patch.

**Comment by WenXin20** [comment]
Also, is it intended for sticks and stones to generate in the end?

**Comment by Jonathing** [comment]
No, they are not intended to generate in the end, I must've forgotten to add that check.
