### ISSUE TITLE
Empty loot chests from unnamed loot tables

### ISSUE THREAD

**Issue by WenXin20** [Jonathing/ForageCraft#75]
`Minecraft v1.16.4`
`Forge v35.1.28`
`Foragecraft v2.1.2`
 
When this mod is run with other mods, it can cause empty loot chests because of the unnamed loot tables. This happens when Minecolonies or Artifacts is installed, and probably other mods too. Enigmatic Legacy made this easier to identify by printing which mods are causing it.
[Error Log](https://gist.github.com/WenXin20/bdc3fe84060896b24a6dfedca91c5ef9#file-loot_table_error-log-L8)

**Comment by Extegral** [comment]
This line of code basically:

https://github.com/Jonathing/ForageCraft/blob/4893c498388a7a3937d051e05abd981ba6f7b9e1/src/main/java/me/jonathing/minecraft/foragecraft/common/handler/GeneralEventHandler.java#L32

You should always name `LootPool`s you inject by calling `LootPool.Builder#name(String)`. Set it to whatever, just make sure that whatever is not `null`.

**Comment by Jonathing** [comment]
@Extegral Thanks for the tip, doing that now.

**Comment by Jonathing** [comment]
That should do the trick. I'll attempt some extensive testing before I release 2.1.3 (or 2.2.0) and if I still fucked something up, I'll re-open this issue. Thanks again for the tip!
